---
title: "groupProject"
author: "Ryan"
date: "`r Sys.Date()`"
output: html_document
---

##Loading libraries
```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(stringr)
library(ggplot2)
```

## Combining Datasets

### Read CSV Files

```{r cars}
forest_km <- read_delim("forest_area_km.csv")
forest_percent <- read_delim("forest_area_percent.csv")
global_temp <- read_delim("Global_Temperatures.csv")
```
### Checking first few columns in each csv
```{r}
head(forest_km,5) 
head(forest_percent,5) 
head(global_temp,5)
```
### Cleaning Up CSV Files
#### Convert "Country Name" header to "country"
```{r}
forest_km <- forest_km %>%
  rename(country = `Country Name`)
  head(forest_km, 5)
```
#### Convert "Country Name" header to "country"
```{r}
forest_percent <- forest_percent %>%
  rename(country = `Country Name`)
  head(forest_km, 5)
```
#### Convert "year" data type from double to char
```{r}
global_temp <- global_temp %>%
  mutate(year = as.character(year))
```

### Convert Forms from wide to long form

```{r}
countryList <- c('country', 'Country Code')

longForestKM <- forest_km %>%
   pivot_longer(!countryList, names_to = "year", values_to = "km")
longForestKM

```
```{r}

longForestPercent <- forest_percent %>%
   pivot_longer(!countryList, names_to = "year", values_to = "percent")
longForestPercent
```
## Joining Table Together for Forest
```{r}
forest_km_percent <- left_join(longForestKM, longForestPercent)
forest_km_percent
```
## Joining global temp together to create a final set
```{r}
final_set <- left_join(global_temp, forest_km_percent)
final_set
```





